import unittest
import os
# Assuming the function to be imported is named extract_first_page_content
# and it's in extract_first_page.py
from extract_first_page import extract_first_page_content

class TestFirstPageExtraction(unittest.TestCase):

    def test_extract_first_page(self):
        # Define file paths
        pdf_path = "2024-Cutoff-Maharashtra.pdf"
        expected_output_path = "standard_expected_first_page_output.csv" # Changed to new standard file
        # Temporary file for the extracted output from the PDF
        actual_output_path = "temp_actual_output.csv"

        # Ensure the PDF file exists before running the test
        self.assertTrue(os.path.exists(pdf_path), f"PDF file not found: {pdf_path}")
        # Ensure the expected output CSV file exists before running the test
        self.assertTrue(os.path.exists(expected_output_path), f"Expected output file not found: {expected_output_path}")

        # Call the function to extract the first page and save it to actual_output_path
        extract_first_page_content(pdf_path, actual_output_path)

        # Read the content of the actual output file (generated by the function)
        with open(actual_output_path, 'rb') as f_actual:
            actual_content = f_actual.read()

        # Read the content of the expected output file
        with open(expected_output_path, 'rb') as f_expected:
            expected_content = f_expected.read()

        # Compare the actual content with the expected content byte-for-byte
        self.assertEqual(actual_content, expected_content,
                         "The extracted first page content does not match the expected output content.")

        # Clean up the temporary actual output file after the test
        if os.path.exists(actual_output_path):
            os.remove(actual_output_path)

if __name__ == '__main__':
    unittest.main()
